---

- name: update and install packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - git
    - vim
    - tmux
    - curl

- name: clone OS-A-D
  git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    dest: /root/os-ansible-deployment
    update: yes
    force: yes
  failed_when: false

# redundancy of env here needs further testing. should be able to remove env
# bits from tmux command
- name: deploy osad aio 
  shell: tmux new -s aio-build -d 'DEPLOY_CEILOMETER=no ./scripts/bootstrap-aio.sh && ./scripts/bootstrap-ansible.sh && ./scripts/run-playbooks.sh'
  args:
    chdir: /opt/os-ansible-deployment
    environment:
      DEPLOY_CEILOMETER=no
    creates: /etc/openstack_deploy

